name: job_portal_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  iconly: ^1.0.1
  font_awesome_flutter: ^10.10.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_radio_group: ^2.1.0

  # Firebase

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_auth_web: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_messaging: ^16.0.1

  # State Management
  provider: ^6.1.5+1

  # File & Media
  path: ^1.9.1
  cloudinary_public: ^0.21.0
  file_picker: ^10.3.3
  image_picker: ^1.2.0

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.0
  terminal_color_parser: ^0.8.0
  logging: ^1.2.0
  http: ^1.2.1
  crypto: ^3.0.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.70.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
