// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpkX5er7K41YaUC0lPhLZT-tuZiVciHkI',
    appId: '1:760039732529:web:dd2f6ecc5c5679a5f32c10',
    messagingSenderId: '760039732529',
    projectId: 'jobportalapp-34abb',
    authDomain: 'jobportalapp-34abb.firebaseapp.com',
    storageBucket: 'jobportalapp-34abb.firebasestorage.app',
    measurementId: 'G-PKH0SSFKEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe6lbOuXWwm93KFVIJ3mW4yMFFd0IPWX4',
    appId: '1:760039732529:android:a12d0e764e08bccaf32c10',
    messagingSenderId: '760039732529',
    projectId: 'jobportalapp-34abb',
    storageBucket: 'jobportalapp-34abb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTTSJTOjRJfz-CguM9w8TDU-IbH79NdY',
    appId: '1:760039732529:ios:04791d22245d3a07f32c10',
    messagingSenderId: '760039732529',
    projectId: 'jobportalapp-34abb',
    storageBucket: 'jobportalapp-34abb.firebasestorage.app',
    iosBundleId: 'com.example.jobPortalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTTSJTOjRJfz-CguM9w8TDU-IbH79NdY',
    appId: '1:760039732529:ios:04791d22245d3a07f32c10',
    messagingSenderId: '760039732529',
    projectId: 'jobportalapp-34abb',
    storageBucket: 'jobportalapp-34abb.firebasestorage.app',
    iosBundleId: 'com.example.jobPortalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpkX5er7K41YaUC0lPhLZT-tuZiVciHkI',
    appId: '1:760039732529:web:4083108a7067d3d1f32c10',
    messagingSenderId: '760039732529',
    projectId: 'jobportalapp-34abb',
    authDomain: 'jobportalapp-34abb.firebaseapp.com',
    storageBucket: 'jobportalapp-34abb.firebasestorage.app',
    measurementId: 'G-CN3GNV583M',
  );
}
