// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-EcV4docSkRP4Va73ZoD8Jsfpfzp85e0',
    appId: '1:686052989460:web:f68917c448b7dc9f186501',
    messagingSenderId: '686052989460',
    projectId: 'jobportalapp-92d76',
    authDomain: 'jobportalapp-92d76.firebaseapp.com',
    databaseURL: 'https://jobportalapp-92d76-default-rtdb.firebaseio.com',
    storageBucket: 'jobportalapp-92d76.firebasestorage.app',
    measurementId: 'G-B1J5X794WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgtzjB4QgQ8MSBHD_t8nB7ZYgmyP2byo',
    appId: '1:686052989460:android:e231d01387d63711186501',
    messagingSenderId: '686052989460',
    projectId: 'jobportalapp-92d76',
    databaseURL: 'https://jobportalapp-92d76-default-rtdb.firebaseio.com',
    storageBucket: 'jobportalapp-92d76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOeLuMDcamG2a-hkZBsu0jyB8fc-rJrSE',
    appId: '1:686052989460:ios:0cd1416bfe5506db186501',
    messagingSenderId: '686052989460',
    projectId: 'jobportalapp-92d76',
    databaseURL: 'https://jobportalapp-92d76-default-rtdb.firebaseio.com',
    storageBucket: 'jobportalapp-92d76.firebasestorage.app',
    iosBundleId: 'com.example.jobPortalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOeLuMDcamG2a-hkZBsu0jyB8fc-rJrSE',
    appId: '1:686052989460:ios:0cd1416bfe5506db186501',
    messagingSenderId: '686052989460',
    projectId: 'jobportalapp-92d76',
    databaseURL: 'https://jobportalapp-92d76-default-rtdb.firebaseio.com',
    storageBucket: 'jobportalapp-92d76.firebasestorage.app',
    iosBundleId: 'com.example.jobPortalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-EcV4docSkRP4Va73ZoD8Jsfpfzp85e0',
    appId: '1:686052989460:web:a80200e69c19597e186501',
    messagingSenderId: '686052989460',
    projectId: 'jobportalapp-92d76',
    authDomain: 'jobportalapp-92d76.firebaseapp.com',
    databaseURL: 'https://jobportalapp-92d76-default-rtdb.firebaseio.com',
    storageBucket: 'jobportalapp-92d76.firebasestorage.app',
    measurementId: 'G-0BDJMJCBYF',
  );
}
